name: Cloud CI Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pytest

      - name: Run Application
        run: python app.py

      - name: Run Tests
        run: pytest
